# Generated by Django 4.2.7 on 2023-11-29 08:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardsweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levels',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
