# Generated by Django 4.2.7 on 2023-11-30 08:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardsweb', '0002_levels_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialities',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
