# Generated by Django 4.2.7 on 2023-12-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardsweb', '0003_specialities_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
