# Generated by Django 4.2.7 on 2023-12-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardsweb', '0004_alter_employees_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='sex',
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
