# Generated by Django 4.2.7 on 2023-12-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardsweb', '0006_alter_employees_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
