# Generated by Django 4.2.7 on 2023-12-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardsweb', '0007_alter_employees_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='id',
            new_name='odoo_id',
        ),
    ]
