# Generated by Django 4.2.7 on 2023-12-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballcardsweb', '0008_rename_id_employees_odoo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='odoo_id',
            new_name='id',
        ),
    ]
